spring:
  datasource:
    url: {{FLAT_DB_URL}}
    username: {{DB_USR}}
    password: {{DB_PSW}}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

app:
  jwt:
    secret: {{JWT_SECRET}}
    issuer: {{REPOSITORY_OWNER}}

urls:
  realt:
    basic: https://realt.by
    rent:
      for-long: https://realt.by/belarus/rent/flat-for-long/
      for-day: https://realt.by/belarus/rent/flat-for-day/
    sales: https://realt.by/belarus/sale/flats/


