version: '2.1'
services:
  user-db:
    build: user-db
    image: user-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitanax
    networks:
      - flats_ntwrk

  sender-db:
    build: sender-db
    image: sender-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitanax
    networks:
      - flats_ntwrk
  flat-db:
    build: flat-db
    image: flat-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitanax
    networks:
      - flats_ntwrk
  audit-db:
    build: audit-db
    image: audit-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitanax
    networks:
      - flats_ntwrk

  sender-service:
    build: sender-service
    image: sender-service:1.0.0
#    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - sender-db
    networks:
      - flats_ntwrk

  user-service:
    build: user-service
    image: user-service:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    networks:
      - flats_ntwrk

  parser-service:
    build: parser-service
    image: parser-service:1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - flat-db
    networks:
      - flats_ntwrk
  flat-service:
    build: flat-service
    image: flat-service:1.0.0
    ports:
      - "8083:8083"
    depends_on:
      - flat-db
    networks:
      - flats_ntwrk
  audit-service:
    build: audit-service
    image: audit-service:1.0.0
    ports:
      - "8084:8084"
    networks:
      - flats_ntwrk

networks:
    flats_ntwrk:
      driver: bridge
# pgadmin:
#   build: pgadmin
#   image: flats_pgadmin:1.0.1
#   restart: always
#   environment:
#     PGADMIN_DEFAULT_EMAIL: admin@admin.com
#     PGADMIN_DEFAULT_PASSWORD: root
#   ports:
#     - "82:80"
#   networks:
#     - flats_ntwrk
# proxy:
#   build: proxy
#   image: flats_proxy:1.0.2
#   ports:
#     - "80:80"
#   networks:
#     - flats_ntwrk


