version: '2.1'
services:
  user-db:
    image: ghcr.io/markmiklash/user-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitanax
    networks:
      - flats_ntwrk

  sender-db:
    image: ghcr.io/markmiklash/sender-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitanax
    networks:
      - flats_ntwrk

  flat-db:
    image: ghcr.io/markmiklash/flat-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitanax
    networks:
      - flats_ntwrk

  audit-db:
    image: ghcr.io/markmiklash/audit-db:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitanax
    networks:
      - flats_ntwrk

  sender-service:
    image: ghcr.io/markmiklash/sender-service:1.0.0
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - sender-db
    networks:
      - flats_ntwrk

  user-service:
    image: ghcr.io/markmiklash/user-service:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    networks:
      - flats_ntwrk

  parser-service:
    image: ghcr.io/markmiklash/parser-service:1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - flat-db
    networks:
      - flats_ntwrk

  flat-service:
    image: ghcr.io/markmiklash/flat-service:1.0.0
    ports:
      - "8083:8083"
    depends_on:
      - flat-db
    networks:
      - flats_ntwrk

  audit-service:
    image: ghcr.io/markmiklash/audit-service:1.0.0
    ports:
      - "8084:8084"
    networks:
      - flats_ntwrk

networks:
  flats_ntwrk:
    driver: bridge
# pgadmin:
#   build: pgadmin
#   image: flats_pgadmin:1.0.1
#   restart: always
#   environment:
#     PGADMIN_DEFAULT_EMAIL: admin@admin.com
#     PGADMIN_DEFAULT_PASSWORD: root
#   ports:
#     - "82:80"
#   networks:
#     - flats_ntwrk
# proxy:
#   build: proxy
#   image: flats_proxy:1.0.2
#   ports:
#     - "80:80"
#   networks:
#     - flats_ntwrk


