spring:
  datasource:
    url: ${{sercets.AUDIT_DB_URL}}
    username: ${{sercets.DB_USR}}
    password: ${{sercets.DB_PSW}}

    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

app:
  jwt:
    secret: ${{sercets.JWT_SECRET}}

  reports:
    dir: /reports