spring:
  datasource:
    url: {{AUDIT_DB_URL}}
    username: {{DB_USR}}
    password: {{DB_PSW}}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

app:
  jwt:
    secret: {{JWT_SECRET}}

  reports:
    dir: /reports
