spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_reportDB
    username: postgres
    password: kitanax

server:
  port: 8084

app:
  reports:
    dir: C:\Users\markm\Desktop\JavaCourses2\FinalProject\FlatSearch App\audit-service\xls_files\