spring:
  datasource:
    url: {{SENDER_DB_URL}}
    username: {{DB_USR}}
    password: {{DB_PSW}}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

app:
  mail:
    host: {{SENDER_SMPT_HOST}}
    port: {{SENDER_SMPT_PORT}}
    username: {{SENDER_SMPT_USERNAME}}
    password: {{SENDER_SMPT_PSW}}
  jwt:
    secret: {{JWT_SECRET}}
    issuer: {{REPOSITORY_OWNER}}
