spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local
  jpa:
    show-sql: true



app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy