spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: prod

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug



app:
  parsing:
    realt:
      basic: https://realt.by
      sales: https://realt.by/sale/flats/
      rentForLong: https://realt.by/rent/flat-for-long/
      rentForDay: https://realt.by/rent/flat-for-day/


