name: CI/CD Pipeline

on:
  push:
jobs:
  install-exceptions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Install exceptions module
        run: cd exceptions && mvn clean install

  test-services:
    runs-on: ubuntu-latest
    needs: install-exceptions
    strategy:
      matrix:
        service: [audit-service, flat-service, parser-service, sender-service, user-service]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Copy local Maven repository
        run: cp -r /home/runner/.m2/repository $HOME/.m2/repository

      - name: Run tests for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          mvn clean test

      - name: Package service JAR
        run: |
          cd ${{ matrix.service }}
          mvn package -DskipTests

      - name: Archive JAR files
        uses: actions/upload-artifact@v3
        with:
          name: jar-files-${{ matrix.service }}
          path: ${{ matrix.service }}/target/*.jar

  build:
    runs-on: ubuntu-latest
    needs: test-services
    strategy:
      matrix:
        service: [audit-service, audit-db, flat-db, flat-service, parser-service, pgadmin, proxy, sender-db, sender-service, user-db, user-service]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Download JAR files
        uses: actions/download-artifact@v3
        with:
          name: jar-files-${{ matrix.service }}
          path: jars

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: false
          tags: user/${{ matrix.service }}:latest
